daemon: true
log:
    displayLevel: 1
    fileLevel: 1
    filePath: .
    activityFilePath: .
    fileRoot: DVM
network:
    enable: true
    id: 100000
    address: 127.0.0.1
    port: 62031
    jitter: 360
    password: "PASSWORD"
    slot1: true
    slot2: true
    updateLookups: false
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    debug: false
    rconEnable: false
    rconAddress: 127.0.0.1
    rconPort: 9990
    rconPassword: "PASSWORD"
    rconDebug: false
protocols:
    dmr:
        enable: true
        beacons:
            enable: false
            interval: 60
            duration: 3
        control: 
            dedicated: false
            enable: false
            slot: 1
        embeddedLCOnly: false
        dumpTAData: true
        dumpDataPacket: false
        repeatDataPacket: true
        dumpCsbkData: false
        verifyReg: false
        nRandWait: 8
        backOff: 1
        callHang: 5
        txHang: 8
        silenceThreshold: 21
        queueSize: 31
        verbose: true
        debug: false
    p25:
        enable: true
        tduPreambleCount: 6
        control:
            enable: false
            ackRequests: true
            dedicated: false
            broadcast: true
            interval: 300
            duration: 1
            disableTSDUMBF: false
            enableTimeDateAnn: false
        voiceOnControl: false
        disableCompositeFlag: false
        inhibitIllegal: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        verifyAff: false
        verifyReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 5
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: true
        localEmergAlarm: false
        sndcpGrant: false
        silenceThreshold: 124
        disableNetworkHDU: false
        emergDisabled: true
        queueSize: 12
        verbose: true
        debug: false
    nxdn:
        enable: false
        control:
            enable: false
            dedicated: false
            broadcast: true
            interval: 300
            duration: 1
        voiceOnControl: false
        disableCompositeFlag: false
        verifyAff: false
        verifyReg: false
        dumpRcchData: false
        callHang: 5
        silenceThreshold: 14
        queueSize: 12
        verbose: true
        debug: false
system:
    identity: ABCD123
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 10
#    rfModeHang: 10
#    netModeHang: 10
#    fixedMode: false
    rfTalkgroupHang: 10
    activeTickDelay: 5
    idleTickDelay: 5
    localTimeOffset: 0
    info:
        latitude: -83.689428
        longitude: -39.194973
        height: 1
        power: 10
        location: "Repeater Site, Antarctica"
    config:
        authoritative: true
        channelId: 2
        channelNo: 1
        dmrNetId: 1
        voiceChNo:
            - channelNo: 1
              rconAddress: 127.0.0.1
              rconPort: 9990
              rconPassword: "PASSWORD"
        colorCode: 1
        nac: 293
#         txNAC: 293
        ran: 1
        pSuperGroup: FFFF
        netId: BB800
        sysId: 001
        rfssId: 1
        siteId: 1
    modem:
        protocol:
            type: "null" # Valid values are "null", and "uart"
            uart:
                port: /dev/ttyUSB0
                speed: 115200
        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 80
        dmrRxDelay: 7
        p25CorrCount: 8
        hotspot:
            dmrDiscBWAdj: 0 # Valid values between -128 and 128
            dmrPostBWAdj: 0 # Valid values between -128 and 128
            p25DiscBWAdj: 0 # Valid values between -128 and 128
            p25PostBWAdj: 0 # Valid values between -128 and 128
            nxdnDiscBWAdj: 0 # Valid values between -128 and 128
            nxdnPostBWAdj: 0 # Valid values between -128 and 128
            adfGainMode: 0 # 0 - Auto, 1 - Auto High Lin, 2 - Low, 3 - High
            afcEnable: false
            afcKI: 11
            afcKP: 4
            afcRange: 1
            txTuning: 0 # Freq offset for the hotspot, in hz
            rxTuning: 0
        repeater:
            dmrSymLvl3Adj: 0 # Valid values between -128 and 128
            dmrSymLvl1Adj: 0 # Valid values between -128 and 128
            p25SymLvl3Adj: 0 # Valid values between -128 and 128
            p25SymLvl1Adj: 0 # Valid values between -128 and 128
            nxdnSymLvl3Adj: 0 # Valid values between -128 and 128
            nxdnSymLvl1Adj: 0 # Valid values between -128 and 128
        softpot:
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
            rssiCoarse: 127
            rssiFine: 127
        rxDCOffset: 0 # Valid values between -128 and 128
        txDCOffset: 0 # Valid values between -128 and 128
        rxLevel: 50
        txLevel: 50
#        cwIdTxLevel: 50
#        dmrTxLevel: 50
#        p25TxLevel: 50
#        nxdnTxLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        dumpModemStatus: false
        trace: false
        debug: false
    cwId:
        enable: true
        time: 15
        callsign: ABCD123
    iden_table:
        file: iden_table.dat
        time: 30
    radio_id:
        file: rid_acl.dat
        time: 2
        acl: false
    talkgroup_id:
        file: tg_acl.dat
        time: 2
        acl: false
