name: dvmhost-build-dpkg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi build-essential devscripts debhelper
        
      - name: Sync Git Submodules
        run: git submodule init && git submodule update
        
      - name: Change /opt Permissions
        run: sudo chmod 777 /opt
        
      - name: Build Debian Package
        run: make dpkg
        
      - name: Package Hash
        run: |
          echo "BRANCH: ${{steps.branch-name.outputs.current_branch}}" >> release.txt
          echo "COMMIT: ${{github.sha}}" >> release.txt
          echo >> release.txt
          echo '```' >> release.txt
          cat << EOF >> release.txt
          dvmhost_1.0.0-1_amd64.deb
          size  : $(wc -c     dvmhost_1.0.0-1_amd64.deb)
          md5   : $(md5sum    dvmhost_1.0.0-1_amd64.deb)
          sha1  : $(sha1sum   dvmhost_1.0.0-1_amd64.deb)
          sha256: $(sha256sum dvmhost_1.0.0-1_amd64.deb)
          EOF
          echo '```' >> release.txt
          
      - name: Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.date.outputs.date}}
          body_path: release.txt
          files: |
            dvmhost_1.0.0-1_amd64.deb
